### ISSUE TITLE
manager role should not be allowed to add new collections

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#61] opened 2017-02-03 16:42 UTC
### Descriptive summary

A user with "manager" role for one collection is able to add new collections and delete collections. Also there are two steps to add a user as a manager which should not be the case.
- We need to add this user as a system wide  manager
- Then add the user to a particular collection as a manager
I feel that the first step is unnecessary, @seanluyk what do you think

### Expected behavior
A "collection manager" should not be allowed to add new collections and it should be a one step process.

### Actual behavior
Current interface allows a manager to add new collections.

### Related work

#60

**Comment by seanluyk** [comment] 2017-02-05 17:33
According to the documentation, managers should be able to add new collections and delete existing ones: 
![image](https://cloud.githubusercontent.com/assets/14880206/22628266/41eb557a-eb8e-11e6-9f76-983c4c8296cf.png)

From https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+Collections+Guide#AvalonCollectionsGuide-CollectionMembersRoles

I think what our issue is is that the editor permissions are not working correctly.

**Comment by umarqasim** [comment] 2017-02-06 20:26
Although the Avalon team has listed these feature, I am seeing the role of a manager from a different perspective. Administrators are super users who are given overall control. Managers on the other hand should be responsible for one collection(super user for that collection). In my view giving them an ability to delete the collection and to add new collections is probably too much control.
I spoke with @weiweishi about this and she is going to share with some information from the Hydra community to check how the larger community thinks about collection manager role.

**Comment by weiweishi** [comment] 2017-02-06 20:31
And here are the six personas Hydra-in-a-Box developed. I don't really see
the "collection manager" but I suppose the researcher role can be expanded
to have the privileges.

https://wiki.duraspace.org/display/hydra/Hydra-in-a-Box+Design+Documents?preview=/76841397/77431615/Hydra-in-a-Box%20Personas.pdf

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by seanluyk** [comment] 2017-02-06 23:48
Yes, let's discuss this one at our grooming meeting @umarqasim. I see what you mean - there is an advantage to having managers who can add/remove editors, but not create/delete collections. On the other hand, we could decide to just fix the editor role and not give out manager roles to anyone external to DI (i.e. we add/remove editors at their request, but the highest they get is an editor role).

**Comment by umarqasim** [comment] 2017-02-07 18:23
@seanluyk @weiweishi 
I have checked the documentation @weiwei shared with us. Also further reviewed the current Avalon role implementation. I feel that a Manager role may be getting more control than we would like and an Editor role has less privileges than they may require. For further elaboration on this, here are two scenarios

## Case Scenario: Manager
cons
- A manager for a collection is able to create as many new collections as he/she likes, this may become a challenge if a manager decides to create more collections without consulting an ERA A+V manager(i.e. Sean or I)
- A manager is able to delete a collection for which he/she is the manager. This can happen accidentally or intentionally and users will loose access.

## Case Scenario: Editor
cons
- An editor is not able to make changes in the access control at the collection level
- An editor is not able to do any thing with published items
- An editor is not able to add more editors to delegate work

@seanluyk Do you think an Editor option can be used, for example in case of Grant Assist Program,  with these limited capabilities. Or a "Manager" role is fine even though they can create new collections and delete any collection.

**Comment by seanluyk** [comment] 2017-02-07 21:13
@umarqasim According to the documentation, editors should be able to set item level access control, which I think is enough for the GAP group. The only thing they would need us for is to add additional editors. The editor role gives them some other abilities (like metadata editing and adding items) which is probably OK too, but we just need to be sure. The issue here is that the editor role has never worked correctly, e.g. the metadata team was not able to add/edit metadata. 

 I don't think we should give anyone external a manager role - it actually allows them to delete **any** collection, from how I understand the documentation. Manager is really intended to be an internal role: Managers are those **within a given unit** who have overall accountability for the collection building within Avalon. Managers create collections and assign editor and depositor roles for those collections. They set the default access controls for items added to a collection and they also step in when a published item needs to be revised or deleted" - this seems to depend on unit for some reason, which may be why it's not working properly? It's a more tiered level of access control.

**Comment by umarqasim** [comment] 2017-02-07 22:30
I agree, giving them a manager role is probably too much of a control unless we strip away some of the capabilities of the manager role. If the Editor role start working like it should, that will work for us for the most part. One limitation that I can see right now is that Editors are not allowed to make any changes with the published content. In some cases this may be ok but in other cases it would add an extra layer of approval.

**Comment by seanluyk** [comment] 2017-05-05 21:45
I've done some more informal tests on roles/permissions and I can confirm that they are not working correctly at all (the only role that works is manager and we don't want to be giving that out to just anyone). As this is core functionality in Avalon and will be important as the service grows, I'd like to move this and the related issue #60 to pre-launch and high priority

**Comment by cwant** [comment] 2017-07-27 15:22
Just to be clear, from reading this, it looks like the proposed plan is to keep the manager role as it is, then "fix" the editor role, and only giving out the editor roles to non-library staff.

As far as I can tell, the editor role works as it was designed to do, and most of the problems revolve around the fact that editors can't edit published content (this is the behaviour described in the upstream documentation). So a decision has to be made as to what to do with the Editor role (please see #60):

1) Keep things as they are, and a manager has to unpublish an item before an editor can work on it again;
2) Allow editors to unpublish items so that they can work on them again; or
3) Allow editors to edit published items.

Until this decision is made, there's nothing more I can do for this issue, or for #60.

**Comment by umarqasim** [comment] 2017-07-27 17:08
Quite an interesting problem. We should assess any negative consequences for giving more power to editors and moving away from the standard permission model in the documentation. From the above three options, I consider option 2 as a comparatively better approach. 

Having said that, we may explore a better use of the "manager" role. Currently there is a confusing requirement to add a manager to any particular collection, first the person has to be added to the site wide manager group. If we can assign managers to individual collections, but not at the site level, this may help in using this role to administer any collection.

**Comment by seanluyk** [comment] 2017-07-27 18:09
Thanks for laying out the options, @cwant. I tend to agree with Umar - option 2 seems to be the best option for the purposes of closing these tickets. Longer term/phase 2 we could reassess the manager and editor roles and see if there's a better solution.

**Comment by cwant** [comment] 2017-08-10 15:31
The "Allow Editor to Unpublish" feature was added in the last release. Should this ticket be closed?

**Comment by seanluyk** [comment] 2017-08-10 15:40
@cwant - yes, this can be closed as the fix to the editor role makes this issue unnecessary. Closing

**Closed by seanluyk** 2017-08-10 15:40 UTC
Labels: permissions, Post-launch, priority:high
